// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"database/sql"
	"time"
)

type Item struct {
	Name        string         `db:"name"`
	DisplayName string         `db:"display_name"`
	CreateTime  time.Time      `db:"create_time"`
	UpdateTime  time.Time      `db:"update_time"`
	DeleteTime  sql.NullTime   `db:"delete_time"`
	Hash        sql.NullString `db:"hash"`
	Content     sql.NullString `db:"content"`
	Properties  interface{}    `db:"properties"`
	Metadata    interface{}    `db:"metadata"`
}
