// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	GetItem(ctx context.Context, name string) (Item, error)
	ListItems(ctx context.Context) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
