services:
  postgres:
    container_name: database
    command: ["postgres", "-c", "log_statement=all", "-c", "wal_level=logical"]
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U develop"] 
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop_secret