openapi: 3.0.0
info:
  title: GlassCMS API
  version: 0.0.0
tags: []
paths:
  /items:
    get:
      operationId: Items_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    delete:
      operationId: Items_delete
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
              required:
                - id
    post:
      operationId: Items_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      required:
        - id
        - name
        - display_name
        - path
        - content
        - create_time
        - update_time
        - properties
      properties:
        id:
          type: string
        name:
          type: string
        display_name:
          type: string
        path:
          type: string
        content:
          type: string
        create_time:
          type: string
          format: date-time
        update_time:
          type: string
          format: date-time
        properties:
          type: object
          additionalProperties: {}
      description: Item represents an individual content item.
