openapi: 3.0.0
info:
  title: GlassCMS API
  version: 0.0.0
tags: []
paths:
  /items:
    post:
      operationId: Items_create
      description: Creates a new item.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '201':
          description: Resource create operation completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCreate'
  /items/{name}:
    get:
      operationId: Items_get
      description: Retrieve an item by its unique identifier.
      parameters:
        - $ref: '#/components/parameters/ItemKey'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    ItemKey:
      name: name
      in: path
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      required:
        - type
        - code
        - message
        - details
      properties:
        type:
          $ref: '#/components/schemas/ErrorType'
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
        details:
          type: object
          additionalProperties: {}
      description: Error is the response model when an API call is unsuccessful.
    ErrorCode:
      type: string
      enum:
        - parameter_invalid
        - parameter_missing
        - processing_error
        - resource_already_exists
        - resource_missing
    ErrorType:
      type: string
      enum:
        - api_error
        - invalid_request_error
    Item:
      type: object
      required:
        - name
        - display_name
        - content
        - create_time
        - update_time
        - delete_time
        - properties
        - metadata
      properties:
        name:
          type: string
        display_name:
          type: string
        content:
          type: string
        create_time:
          type: string
          format: date-time
        update_time:
          type: string
          format: date-time
        delete_time:
          type: string
          format: date-time
          readOnly: true
        properties:
          type: object
          additionalProperties: {}
        metadata:
          type: object
          additionalProperties: {}
      description: Item represents an individual content item.
    ItemCreate:
      type: object
      required:
        - name
        - display_name
        - content
        - create_time
        - update_time
        - properties
        - metadata
      properties:
        name:
          type: string
        display_name:
          type: string
        content:
          type: string
        create_time:
          type: string
          format: date-time
        update_time:
          type: string
          format: date-time
        properties:
          type: object
          additionalProperties: {}
        metadata:
          type: object
          additionalProperties: {}
      description: Resource create operation model.
    Versions:
      type: string
      enum:
        - v1
