openapi: 3.0.0
info:
  title: GlassCMS API
  version: 0.0.0
tags: []
paths:
  /items:
    get:
      operationId: Items_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      operationId: Items_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      required:
        - id
        - name
        - path
        - content
        - created_time
        - update_time
        - props
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        path:
          type: string
        content:
          type: string
        created_time:
          type: string
          format: date-time
        update_time:
          type: string
          format: date-time
        props:
          type: object
          additionalProperties: {}
      description: Item represents an individual content item.
